name: workmanager_example
description: Demonstrates how to use the workmanager plugin.
publish_to: 'none'

environment:
#  sdk: ">=2.12.0-0 <3.0.0"
  sdk: '>=2.19.0-255.2.beta <3.0.0'

dependencies:
  path_provider: ^2.0.11
  shared_preferences: ^2.0.15
  flutter:
    sdk: flutter

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter

  workmanager:
    path: ../

flutter:
  uses-material-design: true